= DeltaSpike Release Notes v1.0.3

:toc:

== Announcement

The DeltaSpike team is proud to announce the release of v1.0.3.  See http://apache-deltaspike-incubator-discussions.2316169.n4.nabble.com/ANNOUNCE-Release-of-Apache-DeltaSpike-1-0-3-td4659029.html[our release announcement email^] for additional information.

Please read our <<index.adoc#_getting_started,setup guide>> to add DeltaSpike to your application.

== Highlights

=== Code Changes

  - Multiple improvements and fixes to our JSF Support
    - Fixes around client window handling with JSF Native & Primefaces AJAX
    - Window ID handling now works properly with lazy configuration
  - Exception handling has been improved; better cross module support, JSF integration for Exceptions is improved.
  - CDI versions are no longer included directly in any profile, to help with running applications against CDI 1.1/1.2 runtimes
  - `BeanManagerProvider` will automatically use a child's classloader for `BeanManager` detection in case none found for the parent.

=== Documentation Changes

Several important documentation changes went in as well

  - Scope availability in the core module
  - Documentation around Security and PicketLink
  - The first steps to moving our documentation to asciidoc has been performed

== Credits & Thanks

  - Thanks to all those that contributed via https://www.openhub.net/p/DeltaSpike/contributors?query=&sort=latest_commit[OpenHub^]
  - Thanks to those who reviewed and http://apache-deltaspike-incubator-discussions.2316169.n4.nabble.com/VOTE-Release-of-Apache-DeltaSpike-1-0-3-td4658987.html[voted^] on the release

== Full Release Notes
++++
<h3>        Bug
</h3>
<ul>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-696'>DELTASPIKE-696</a>] -         Remove unneeded dependencies on CDICtrl Servlet
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-706'>DELTASPIKE-706</a>] -         Multiple CDI API versions on classpath in JSF module tests (Weld)
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-710'>DELTASPIKE-710</a>] -         Error using clientWindow and (p|f):ajax
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-717'>DELTASPIKE-717</a>] -         Exception handlers not invoked when @Secured ViewConfig is violated in an app with JSF module without a DefaultErrorView page
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-719'>DELTASPIKE-719</a>] -         Only one voter invoked if multiple voters are applied through a stereotype
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-723'>DELTASPIKE-723</a>] -         Exception bypassing on JSF conversion errors
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-726'>DELTASPIKE-726</a>] -         Lazy window handling doesn&#39;t recognize new windows anymore
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-729'>DELTASPIKE-729</a>] -         f:viewAction is executed twice with LAZY window handling mode
</li>
</ul>

<h3>        Improvement
</h3>
<ul>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-692'>DELTASPIKE-692</a>] -         workaround for tests which don&#39;t use optional classes
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-699'>DELTASPIKE-699</a>] -         Signature relaxing of attribute method() in CriteriaSupport
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-708'>DELTASPIKE-708</a>] -         Veto the AbstractEntityRepository class
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-712'>DELTASPIKE-712</a>] -         BeanManagerProvider : Wrap usage in parent class loaders
</li>
</ul>

<h3>        New Feature
</h3>
<ul>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-702'>DELTASPIKE-702</a>] -         Add support to GreaterThan and LessThan in criteria to dates
</li>
</ul>

<h3>        Task
</h3>
<ul>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-640'>DELTASPIKE-640</a>] -         Document Scopes in Core module
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-677'>DELTASPIKE-677</a>] -         document ds-security in combination with picketlink
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-697'>DELTASPIKE-697</a>] -         Set the baseDir to reside in the target directory for tomcat tests.
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-698'>DELTASPIKE-698</a>] -         re-visit glassfish4 profile
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-711'>DELTASPIKE-711</a>] -         Create placeholder documentation directory
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-716'>DELTASPIKE-716</a>] -         Migrate documentation format to asciidoc at git repo
</li>
<li>[<a href='https://issues.apache.org/jira/browse/DELTASPIKE-730'>DELTASPIKE-730</a>] -         release notes for v1.0.3
</li>
</ul>

++++