= JPA Module

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

:toc:

== Overview
The JPA module provides a transactional context and scope, enabling execution of methods within transactions.

== Configure Your Projects
The configuration information provided here is for Maven-based projects and it assumes that you have already declared the DeltaSpike version and DeltaSpike Core module for your projects, as detailed in <<configure#, Configure DeltaSpike in Your Projects>>. For Maven-independent projects, see <<configure#config-maven-indep,Configure DeltaSpike in Maven-independent Projects>>.

=== 1. Declare JPA Module Dependencies
Add the JPA module to the list of dependencies in the project `pom.xml` file using this code snippet:

[source,xml]
----
<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-jpa-module-api</artifactId>
    <version>${deltaspike.version}</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-jpa-module-impl</artifactId>
    <version>${deltaspike.version}</version>
    <scope>runtime</scope>
</dependency>
----

=== 2. Enable the Transaction Interceptor
For CDI 1.0 (or DeltaSpike v1.1.0 and earlier together with CDI 1.1+), you must enable the transaction interceptor in the project `beans.xml` file:

[source,xml]
----
<beans>
    <!-- Not needed with CDI 1.1+ and DeltaSpike v1.1.1+ -->
    <interceptors>
        <class>org.apache.deltaspike.jpa.impl.transaction.TransactionalInterceptor</class>
    </interceptors>
</beans>
----

== Use the Module Features

=== @Transactional

This annotation is an alternative to transactional EJBs which allows to
execute a method within a transaction. Before it is possible to start
using the annotation, it is required to implement a CDI producer for an
`EntityManager` and it is needed to inject the `EntityManager` in the
bean which uses `@Transactional`. As shown later on, it is also possible
to use multiple qualifiers for using different `EntityManager`s.

The following example shows a simple producer for an `EntityManager` and
the corresponding dispose-method. Producing it as request scoped bean
means that the dispose method will be called on finishing the request.
As an alternative it is possible to use a special scope called
`@TransactionScoped` provided by the same DeltaSpike module.

.Producer for the Default EntityManager (**no EE-Server**)
[source,java]
----------------------------------------------------------------------------
//...
public class EntityManagerProducer
{
    //or manual bootstrapping
    @PersistenceContext
    private EntityManager entityManager;

    @Produces
    @RequestScoped
    protected EntityManager createEntityManager()
    {
        return this.entityManager;
    }

    protected void closeEntityManager(@Disposes EntityManager entityManager)
    {
        if (entityManager.isOpen())
        {
            entityManager.close();
        }
    }
}
----------------------------------------------------------------------------

.Producer for the Default EntityManager (**EE-Server**)
[source,java]
-----------------------------------------------------------------------
@ApplicationScoped
public class EntityManagerProducer
{
    @PersistenceUnit
    private EntityManagerFactory entityManagerFactory;

    @Produces
    @Default
    @RequestScoped
    public EntityManager create()
    {
        return this.entityManagerFactory.createEntityManager();
    }

    public void dispose(@Disposes @Default EntityManager entityManager)
    {
        if (entityManager.isOpen())
        {
            entityManager.close();
        }
    }
}
-----------------------------------------------------------------------

The following examples show how to use the `EntityManager` produced by
the example above.

.Beans with Transactional Method
[source,java]
----------------------------------------
//...
public class TransactionalBean
{
    @Inject
    private EntityManager entityManager;

    @Transactional
    public void executeInTransaction()
    {
        //...
    }
}
----------------------------------------

.Simple Transactional Bean (All Methods are Transactional)
[source,java]
----------------------------------------
//...
@Transactional
public class TransactionalBean
{
    @Inject
    private EntityManager entityManager;

    //...
}
----------------------------------------

As illustrated in the following example it is also possible to use
`@Transactional` for stereotypes.

.Stereotype for Transactional Beans (+ Usage)
[source,java]
----------------------------------------
@Stereotype
@Transactional
@ApplicationScoped
public @interface Repository
{
}

//...
@Repository
public class TransactionalBean
{
    @Inject
    private EntityManager entityManager;

    //...
}
----------------------------------------

Besides such simple usages, it is also supported to use qualifiers to
access multiple persistence-units in parallel. The default qualifier for
`@Transactional` is `@Any`. Therefore a transaction for every injected
entity manager will be started. The example afterwards shows how to
change this default behaviour.

.Producer for Multiple Entity Managers (+ Usage)
[source,java]
------------------------------------------------------------------------------------------
//...
public class EntityManagerProducer
{
    @PersistenceContext(unitName = "firstDB")
    private EntityManager firstEntityManager;

    @PersistenceContext(unitName = "secondDB")
    private EntityManager secondEntityManager;

    @Produces
    @First
    @RequestScoped
    protected EntityManager createFirstEntityManager()
    {
        return this.firstEntityManager;
    }

    protected void closeFirstEntityManager(@Disposes @First EntityManager entityManager)
    {
        if (entityManager.isOpen())
        {
            entityManager.close();
        }
    }

    @Produces
    @Second
    @RequestScoped
    protected EntityManager createSecondEntityManager()
    {
        return this.secondEntityManager;
    }

    protected void closeSecondEntityManager(@Disposes @Second EntityManager entityManager)
    {
        if (entityManager.isOpen())
        {
            entityManager.close();
        }
    }
}

//...
public class FirstLevelTransactionBean
{
    @Inject
    private @First EntityManager firstEntityManager;

    @Inject
    private NestedTransactionBean nestedTransactionBean;

    @Transactional
    public void executeInTransaction()
    {
        //...
        this.nestedTransactionBean.executeInTransaction();
    }
}

//...
public class NestedTransactionBean
{
    @Inject
    private @Second EntityManager secondEntityManager;

    @Transactional
    public void executeInTransaction()
    {
        //...
    }
}
------------------------------------------------------------------------------------------

The following example shows how to use only the specified
`EntityManager`/s

.Activating Entity Managers Manually
[source,java]
-----------------------------------------------------------
public class MultiTransactionBean
{
    @Inject
    private EntityManager defaultEntityManager;

    @Inject
    private @First EntityManager firstEntityManager;

    @Inject
    private @Second EntityManager secondEntityManager;

    @Transactional(qualifier = Default.class)
    public void executeInDefaultTransaction()
    {
    }

    @Transactional(qualifier = First.class)
    public void executeInFirstTransaction()
    {
    }

    @Transactional(qualifier = Second.class)
    public void executeInSecondTransaction()
    {
    }

    @Transactional(qualifier = {First.class, Second.class})
    public void executeInFirstAndSecondTransaction()
    {
    }
}
-----------------------------------------------------------

All examples also work with nested calls. In the following example the
transaction handling is done on the entry point (after
FirstLevelTransactionBean#executeInTransaction).

.Joining Existing Transaction in Nested Call
[source,java]
----------------------------------------------------------
//...
public class FirstLevelTransactionBean
{
    @Inject
    private EntityManager entityManager;

    @Inject
    private NestedTransactionBean nestedTransactionBean;

    @Transactional
    public void executeInTransaction()
    {
        this.nestedTransactionBean.executeInTransaction();
    }
}

//...
public class NestedTransactionBean
{
    @Inject
    private EntityManager entityManager;

    @Transactional
    public void executeInTransaction()
    {
        //...
    }
}
----------------------------------------------------------

The final transaction handling for all `EntityManager` s is also done
after the outermost transactional method if `NestedTransactionBean` uses
a different `EntityManager`. So it is possible to catch an exception in
`FirstLevelTransactionBean`, for example, to try an optional path instead of an
immediate rollback.

=== @TransactionScoped

`@Transactional` also starts a context which is available as long as the
transaction started by `@Transactional`. Besides other beans you can use
this scope for the `EntityManager` itself. That means the
`EntityManager` will be closed after leaving the method annotated with
`@Transactional`.

.Producer for the Default EntityManager which should be Used Only for One
Transaction
[source,java]
----------------------------------------------------------------------------
//...
public class EntityManagerProducer
{
    //or manual bootstrapping
    @PersistenceContext
    private EntityManager entityManager;

    @Produces
    @TransactionScoped
    protected EntityManager createEntityManager()
    {
        return this.entityManager;
    }

    protected void closeEntityManager(@Disposes EntityManager entityManager)
    {
        if (entityManager.isOpen())
        {
            entityManager.close();
        }
    }
}
----------------------------------------------------------------------------

=== Extended Persistence Contexts

Frameworks like MyFaces Orchestra provide a feature which allows keeping
an `EntityManager` across multiple requests. That means it is not
required to call `EntityManager#merge` to add detached entities to the
context. However, several application architectures do not allow such an
approach (due to different reasons like scalability). In theory that
sounds nice and it works pretty well for small to medium sized projects
especially if an application does not rely on session replication in clusters.
That also means that such an approach restricts your target environment
from the very beginning. One of the base problems is that an
`EntityManager` is not serializable. Beans which are scoped in a
normal-scoped CDI context have to be serializable. So by default it
is not allowed by CDI to provide a producer-method which exposes, for example, a
conversation scoped `EntityManager` as it is. We *do not* recommend this approach and therefore it is not available out-of-the-box.
However, if you really need this approach to avoid calling `#merge` for
your detached entities, it is pretty simple to add this functionality.

.Usage of a Simple `ExtendedEntityManager`
[source,java]
------------------------------------
@Inject
private EntityManager entityManager;
------------------------------------

As you see the usage is the same. You *do not* have to use
`ExtendedEntityManager` at the injection point. It is just needed in the
producer-method:

.Producer for the Default Extended-`EntityManager` (**no EE-Server**)
[source,java]
------------------------------------------------------------------------------------
//...
public class ExtendedEntityManagerProducer
{
    //or manual bootstrapping
    @PersistenceContext
    private EntityManager entityManager;

    @Produces
    @RequestScoped
    protected ExtendedEntityManager createEntityManager()
    {
        return new ExtendedEntityManager(this.entityManager);
    }

    protected void closeEntityManager(@Disposes ExtendedEntityManager entityManager)
    {
        if (entityManager.isOpen())
        {
            entityManager.close();
        }
    }
}
------------------------------------------------------------------------------------

.Producer for the Default Extended-`EntityManager` (**EE-Server**)
[source,java]
------------------------------------------------------------------------------------------
@ApplicationScoped
public class ExtendedEntityManagerProducer
{
    @PersistenceUnit
    private EntityManagerFactory entityManagerFactory;

    @Produces
    @Default
    @RequestScoped
    public ExtendedEntityManager create()
    {
        return new ExtendedEntityManager(this.entityManagerFactory.createEntityManager());
    }

    public void dispose(@Disposes @Default ExtendedEntityManager entityManager)
    {
        if (entityManager.isOpen())
        {
            entityManager.close();
        }
    }
}
------------------------------------------------------------------------------------------

.Implementation of a Simple `ExtendedEntityManager`
[source,java]
-------------------------------------------------------------------------
@Typed()
public class ExtendedEntityManager implements EntityManager, Serializable
{
    private static final long serialVersionUID = 3770954229283539616L;

    private transient EntityManager wrapped;

    protected ExtendedEntityManager()
    {
    }

    public ExtendedEntityManager(EntityManager wrapped)
    {
        this.wrapped = wrapped;
    }

    /*
     * generated
     */
    //delegate all calls to this.wrapped - most IDEs allow to generate it
}
-------------------------------------------------------------------------

This approach just works if it *does not come to serialization* of this
wrapper, for example in case of session-replication. If those beans get
serialized, you have to overcome this restriction by storing the
persistence-unit-name and recreate the `EntityManager` via
`Persistence.createEntityManagerFactory(this.persistenceUnitName).createEntityManager();`
and sync it with the database before closing it on serialization.
Furthermore, you have to intercept some methods of the `EntityManager`
to merge detached entities automatically if those entities get
serialized as well. However, as mentioned before *we do not recommend*
such an approach.

=== JTA Support

By default the transaction-type used by `@Transactional` is
`RESOURCE_LOCAL`. If you configure `transaction-type="JTA"` in the
persistence.xml file, you have to enable an alternative `TransactionStrategy`
in the beans.xml which is called
`org.apache.deltaspike.jpa.impl.transaction.BeanManagedUserTransactionStrategy`.

[source,xml]
----------------------------------------------------------------------------------------------------
<beans>
    <alternatives>
        <class>org.apache.deltaspike.jpa.impl.transaction.BeanManagedUserTransactionStrategy</class>
    </alternatives>
</beans>
----------------------------------------------------------------------------------------------------

If you have multiple persistence-units and you have to use both
transaction-types or the settings for development have to be different
than the production settings, you can use
`org.apache.deltaspike.jpa.impl.transaction.EnvironmentAwareTransactionStrategy`
instead.

NOTE: In case of some versions of Weld (or OpenWebBeans in BDA mode), you have
to configure it as global-alternative instead of an `<alternatives>` in
beans.xml. That means you have to add, for example,
`globalAlternatives.org.apache.deltaspike.jpa.spi.transaction.TransactionStrategy 
=org.apache.deltaspike.jpa.impl.transaction.BeanManagedUserTransactionStrategy`
to `/META-INF/apache-deltaspike.properties`
